# Generated by Django 2.1.4 on 2018-12-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SoundRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('isrc', models.CharField(blank=True, max_length=12)),
                ('length', models.CharField(blank=True, max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoundRecordingInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('isrc', models.CharField(blank=True, max_length=12)),
                ('length', models.CharField(blank=True, max_length=12)),
                ('matches', models.ManyToManyField(related_name='matchesByScore', through='soundRecordingsApp.SimilarityScores', to='soundRecordingsApp.SoundRecording')),
                ('selectedCandidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='soundRecordingsApp.SoundRecording')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='similarityscores',
            name='soundRecording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soundRecordingMatches', to='soundRecordingsApp.SoundRecording'),
        ),
        migrations.AddField(
            model_name='similarityscores',
            name='soundRecordingInput',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soundInputMatches', to='soundRecordingsApp.SoundRecordingInput'),
        ),
    ]
