# Generated by Django 2.1.4 on 2018-12-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundRecordingsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundrecording',
            name='isrc',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='soundrecordinginput',
            name='isrc',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
