# Generated by Django 2.1.4 on 2018-12-31 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soundRecordingsApp', '0002_auto_20181226_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundrecordinginput',
            name='selectedCandidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soundRecordingsApp.SoundRecording'),
        ),
    ]
