version: '3'

services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    ports:
      - 9200:9200
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "./wait-for-it.sh host:5432 -t 10 -- ./wait-for-it.sh host:9200 -t 5 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/bmatProject
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch